service: serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: dev
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline

functions:  
  todos:
    handler: src/api/todos.handler
    events:
      - http:
          path: todo
          method: get
  todo:
    handler: src/api/todo.handler
    events:
      - http:
          path: todo/{todo}
          method: get
          request:
            parameters:
              paths:
                todo: true
