service: serverless

provider:
  name: aws
  profile: serverless-with-aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true


plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/api.handler
    events:
      - http: ANY /
      - http: "ANY /{param+}"

  # # todos:
  # #   handler: src/api/todos.handler
  # #   events:
  # #     - http:
  # #         path: /todos
  # #         method: GET

  # # todo:
  #   handler: src/api/todo.handler
  #   events:
  #     - http:
  #         path: /todo/{id}
  #         method: GET
  #         request:
  #           parameters:
  #             id: true


  helloworld:
    handler: src/helloworld.handler
    


